// @generated by scripts/generate-option-schema.py. Do not edit.
//
// Regenerate against a newer tmux to see exactly what changed:
//   python3 scripts/generate-option-schema.py <tmux>/options-table.c

use super::{OptionKind, OptionSchema, OptionScope};

/// Every option tmux's table declares, sorted by name.
pub(crate) static OPTION_SCHEMA: [OptionSchema; 217] = [
    OptionSchema::new("activity-action", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("after-bind-key", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "after-capture-pane",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("after-copy-mode", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "after-display-message",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-display-panes",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("after-kill-pane", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "after-list-buffers",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-list-clients",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("after-list-keys", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "after-list-panes",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-list-sessions",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-list-windows",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-load-buffer",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-lock-server",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-new-session",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-new-window",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-paste-buffer",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("after-pipe-pane", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("after-queue", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "after-refresh-client",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-rename-session",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-rename-window",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-resize-pane",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-resize-window",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-save-buffer",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-select-layout",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-select-pane",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-select-window",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("after-send-keys", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "after-set-buffer",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-set-environment",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("after-set-hook", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "after-set-option",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-show-environment",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-show-messages",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-show-options",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-split-window",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "after-unbind-key",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("aggressive-resize", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("alert-activity", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("alert-bell", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("alert-silence", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("allow-passthrough", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new("allow-rename", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("allow-set-title", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("alternate-screen", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new(
        "assume-paste-time",
        OptionKind::Number,
        OptionScope::Session,
    ),
    OptionSchema::new("automatic-rename", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new(
        "automatic-rename-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("backspace", OptionKind::Key, OptionScope::Server),
    OptionSchema::new("base-index", OptionKind::Number, OptionScope::Session),
    OptionSchema::new("bell-action", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("buffer-limit", OptionKind::Number, OptionScope::Server),
    OptionSchema::new("client-active", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("client-attached", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "client-dark-theme",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("client-detached", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("client-focus-in", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "client-focus-out",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "client-light-theme",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("client-resized", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "client-session-changed",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("clock-mode-colour", OptionKind::Colour, OptionScope::Window),
    OptionSchema::new("clock-mode-style", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new("codepoint-widths", OptionKind::Text, OptionScope::Server),
    OptionSchema::new("command-alias", OptionKind::Text, OptionScope::Server),
    OptionSchema::new("command-error", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("copy-command", OptionKind::Text, OptionScope::Server),
    OptionSchema::new(
        "copy-mode-current-line-number-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-current-match-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-line-number-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-line-numbers",
        OptionKind::Choice,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-mark-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-match-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-position-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-position-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "copy-mode-selection-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("cursor-colour", OptionKind::Colour, OptionScope::Window),
    OptionSchema::new("cursor-style", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new(
        "default-client-command",
        OptionKind::Command,
        OptionScope::Server,
    ),
    OptionSchema::new("default-command", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("default-shell", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("default-size", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("default-terminal", OptionKind::Text, OptionScope::Server),
    OptionSchema::new(
        "destroy-unattached",
        OptionKind::Choice,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "detach-on-destroy",
        OptionKind::Choice,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "display-panes-active-colour",
        OptionKind::Colour,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "display-panes-colour",
        OptionKind::Colour,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "display-panes-time",
        OptionKind::Number,
        OptionScope::Session,
    ),
    OptionSchema::new("display-time", OptionKind::Number, OptionScope::Session),
    OptionSchema::new("editor", OptionKind::Text, OptionScope::Server),
    OptionSchema::new("escape-time", OptionKind::Number, OptionScope::Server),
    OptionSchema::new("exit-empty", OptionKind::Flag, OptionScope::Server),
    OptionSchema::new("exit-unattached", OptionKind::Flag, OptionScope::Server),
    OptionSchema::new("extended-keys", OptionKind::Choice, OptionScope::Server),
    OptionSchema::new(
        "extended-keys-format",
        OptionKind::Choice,
        OptionScope::Server,
    ),
    OptionSchema::new("fill-character", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("focus-events", OptionKind::Flag, OptionScope::Server),
    OptionSchema::new(
        "focus-follows-mouse",
        OptionKind::Flag,
        OptionScope::Session,
    ),
    OptionSchema::new("get-clipboard", OptionKind::Choice, OptionScope::Server),
    OptionSchema::new("history-file", OptionKind::Text, OptionScope::Server),
    OptionSchema::new("history-limit", OptionKind::Number, OptionScope::Session),
    OptionSchema::new(
        "initial-repeat-time",
        OptionKind::Number,
        OptionScope::Session,
    ),
    OptionSchema::new("input-buffer-size", OptionKind::Number, OptionScope::Server),
    OptionSchema::new("key-table", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("lock-after-time", OptionKind::Number, OptionScope::Session),
    OptionSchema::new("lock-command", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("main-pane-height", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("main-pane-width", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("menu-border-lines", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new("menu-border-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("menu-selected-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("menu-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new(
        "message-command-style",
        OptionKind::Text,
        OptionScope::Session,
    ),
    OptionSchema::new("message-format", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("message-limit", OptionKind::Number, OptionScope::Server),
    OptionSchema::new("message-line", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("message-style", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("mode-keys", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new("mode-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("monitor-activity", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("monitor-bell", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("monitor-silence", OptionKind::Number, OptionScope::Window),
    OptionSchema::new("mouse", OptionKind::Flag, OptionScope::Session),
    OptionSchema::new("other-pane-height", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("other-pane-width", OptionKind::Text, OptionScope::Window),
    OptionSchema::new(
        "pane-active-border-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("pane-base-index", OptionKind::Number, OptionScope::Window),
    OptionSchema::new("pane-border-format", OptionKind::Text, OptionScope::Window),
    OptionSchema::new(
        "pane-border-indicators",
        OptionKind::Choice,
        OptionScope::Window,
    ),
    OptionSchema::new("pane-border-lines", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new(
        "pane-border-status",
        OptionKind::Choice,
        OptionScope::Window,
    ),
    OptionSchema::new("pane-border-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("pane-colours", OptionKind::Colour, OptionScope::Window),
    OptionSchema::new("pane-died", OptionKind::Command, OptionScope::Pane),
    OptionSchema::new("pane-exited", OptionKind::Command, OptionScope::Pane),
    OptionSchema::new("pane-focus-in", OptionKind::Command, OptionScope::Pane),
    OptionSchema::new("pane-focus-out", OptionKind::Command, OptionScope::Pane),
    OptionSchema::new("pane-mode-changed", OptionKind::Command, OptionScope::Pane),
    OptionSchema::new("pane-scrollbars", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new(
        "pane-scrollbars-position",
        OptionKind::Choice,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "pane-scrollbars-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("pane-set-clipboard", OptionKind::Command, OptionScope::Pane),
    OptionSchema::new(
        "pane-status-current-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("pane-status-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("pane-title-changed", OptionKind::Command, OptionScope::Pane),
    OptionSchema::new(
        "popup-border-lines",
        OptionKind::Choice,
        OptionScope::Window,
    ),
    OptionSchema::new("popup-border-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("popup-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("prefix", OptionKind::Key, OptionScope::Session),
    OptionSchema::new("prefix-timeout", OptionKind::Number, OptionScope::Server),
    OptionSchema::new("prefix2", OptionKind::Key, OptionScope::Session),
    OptionSchema::new(
        "prompt-command-cursor-style",
        OptionKind::Choice,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "prompt-cursor-colour",
        OptionKind::Colour,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "prompt-cursor-style",
        OptionKind::Choice,
        OptionScope::Session,
    ),
    OptionSchema::new(
        "prompt-history-limit",
        OptionKind::Number,
        OptionScope::Server,
    ),
    OptionSchema::new("remain-on-exit", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new(
        "remain-on-exit-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("renumber-windows", OptionKind::Flag, OptionScope::Session),
    OptionSchema::new("repeat-time", OptionKind::Number, OptionScope::Session),
    OptionSchema::new("scroll-on-clear", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("session-closed", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("session-created", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("session-renamed", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "session-status-current-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "session-status-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "session-window-changed",
        OptionKind::Command,
        OptionScope::Session,
    ),
    OptionSchema::new("set-clipboard", OptionKind::Choice, OptionScope::Server),
    OptionSchema::new("set-titles", OptionKind::Flag, OptionScope::Session),
    OptionSchema::new("set-titles-string", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("silence-action", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("status", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("status-bg", OptionKind::Colour, OptionScope::Session),
    OptionSchema::new("status-fg", OptionKind::Colour, OptionScope::Session),
    OptionSchema::new("status-format", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("status-interval", OptionKind::Number, OptionScope::Session),
    OptionSchema::new("status-justify", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("status-keys", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("status-left", OptionKind::Text, OptionScope::Session),
    OptionSchema::new(
        "status-left-length",
        OptionKind::Number,
        OptionScope::Session,
    ),
    OptionSchema::new("status-left-style", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("status-position", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("status-right", OptionKind::Text, OptionScope::Session),
    OptionSchema::new(
        "status-right-length",
        OptionKind::Number,
        OptionScope::Session,
    ),
    OptionSchema::new("status-right-style", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("status-style", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("synchronize-panes", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("terminal-features", OptionKind::Text, OptionScope::Server),
    OptionSchema::new("terminal-overrides", OptionKind::Text, OptionScope::Server),
    OptionSchema::new(
        "tiled-layout-max-columns",
        OptionKind::Number,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "tree-mode-preview-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "tree-mode-preview-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("update-environment", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("user-keys", OptionKind::Text, OptionScope::Server),
    OptionSchema::new(
        "variation-selector-always-wide",
        OptionKind::Flag,
        OptionScope::Server,
    ),
    OptionSchema::new("visual-activity", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("visual-bell", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("visual-silence", OptionKind::Choice, OptionScope::Session),
    OptionSchema::new("window-active-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("window-linked", OptionKind::Command, OptionScope::Session),
    OptionSchema::new(
        "window-pane-current-status-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "window-pane-status-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("window-size", OptionKind::Choice, OptionScope::Window),
    OptionSchema::new(
        "window-status-activity-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "window-status-bell-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "window-status-current-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "window-status-current-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "window-status-format",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "window-status-last-style",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new(
        "window-status-separator",
        OptionKind::Text,
        OptionScope::Window,
    ),
    OptionSchema::new("window-status-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("window-style", OptionKind::Text, OptionScope::Window),
    OptionSchema::new("window-unlinked", OptionKind::Command, OptionScope::Session),
    OptionSchema::new("word-separators", OptionKind::Text, OptionScope::Session),
    OptionSchema::new("wrap-search", OptionKind::Flag, OptionScope::Window),
    OptionSchema::new("xterm-keys", OptionKind::Flag, OptionScope::Window),
];

/// Option names, so a typo is a compile error rather than a runtime one.
///
/// Every constant here is a name tmux declares. A user option, whose name
/// begins with `@`, has no constant because tmux does not declare one.
pub mod names {
    /// tmux's `activity-action` option.
    pub const ACTIVITY_ACTION: &str = "activity-action";
    /// tmux's `after-bind-key` option.
    pub const AFTER_BIND_KEY: &str = "after-bind-key";
    /// tmux's `after-capture-pane` option.
    pub const AFTER_CAPTURE_PANE: &str = "after-capture-pane";
    /// tmux's `after-copy-mode` option.
    pub const AFTER_COPY_MODE: &str = "after-copy-mode";
    /// tmux's `after-display-message` option.
    pub const AFTER_DISPLAY_MESSAGE: &str = "after-display-message";
    /// tmux's `after-display-panes` option.
    pub const AFTER_DISPLAY_PANES: &str = "after-display-panes";
    /// tmux's `after-kill-pane` option.
    pub const AFTER_KILL_PANE: &str = "after-kill-pane";
    /// tmux's `after-list-buffers` option.
    pub const AFTER_LIST_BUFFERS: &str = "after-list-buffers";
    /// tmux's `after-list-clients` option.
    pub const AFTER_LIST_CLIENTS: &str = "after-list-clients";
    /// tmux's `after-list-keys` option.
    pub const AFTER_LIST_KEYS: &str = "after-list-keys";
    /// tmux's `after-list-panes` option.
    pub const AFTER_LIST_PANES: &str = "after-list-panes";
    /// tmux's `after-list-sessions` option.
    pub const AFTER_LIST_SESSIONS: &str = "after-list-sessions";
    /// tmux's `after-list-windows` option.
    pub const AFTER_LIST_WINDOWS: &str = "after-list-windows";
    /// tmux's `after-load-buffer` option.
    pub const AFTER_LOAD_BUFFER: &str = "after-load-buffer";
    /// tmux's `after-lock-server` option.
    pub const AFTER_LOCK_SERVER: &str = "after-lock-server";
    /// tmux's `after-new-session` option.
    pub const AFTER_NEW_SESSION: &str = "after-new-session";
    /// tmux's `after-new-window` option.
    pub const AFTER_NEW_WINDOW: &str = "after-new-window";
    /// tmux's `after-paste-buffer` option.
    pub const AFTER_PASTE_BUFFER: &str = "after-paste-buffer";
    /// tmux's `after-pipe-pane` option.
    pub const AFTER_PIPE_PANE: &str = "after-pipe-pane";
    /// tmux's `after-queue` option.
    pub const AFTER_QUEUE: &str = "after-queue";
    /// tmux's `after-refresh-client` option.
    pub const AFTER_REFRESH_CLIENT: &str = "after-refresh-client";
    /// tmux's `after-rename-session` option.
    pub const AFTER_RENAME_SESSION: &str = "after-rename-session";
    /// tmux's `after-rename-window` option.
    pub const AFTER_RENAME_WINDOW: &str = "after-rename-window";
    /// tmux's `after-resize-pane` option.
    pub const AFTER_RESIZE_PANE: &str = "after-resize-pane";
    /// tmux's `after-resize-window` option.
    pub const AFTER_RESIZE_WINDOW: &str = "after-resize-window";
    /// tmux's `after-save-buffer` option.
    pub const AFTER_SAVE_BUFFER: &str = "after-save-buffer";
    /// tmux's `after-select-layout` option.
    pub const AFTER_SELECT_LAYOUT: &str = "after-select-layout";
    /// tmux's `after-select-pane` option.
    pub const AFTER_SELECT_PANE: &str = "after-select-pane";
    /// tmux's `after-select-window` option.
    pub const AFTER_SELECT_WINDOW: &str = "after-select-window";
    /// tmux's `after-send-keys` option.
    pub const AFTER_SEND_KEYS: &str = "after-send-keys";
    /// tmux's `after-set-buffer` option.
    pub const AFTER_SET_BUFFER: &str = "after-set-buffer";
    /// tmux's `after-set-environment` option.
    pub const AFTER_SET_ENVIRONMENT: &str = "after-set-environment";
    /// tmux's `after-set-hook` option.
    pub const AFTER_SET_HOOK: &str = "after-set-hook";
    /// tmux's `after-set-option` option.
    pub const AFTER_SET_OPTION: &str = "after-set-option";
    /// tmux's `after-show-environment` option.
    pub const AFTER_SHOW_ENVIRONMENT: &str = "after-show-environment";
    /// tmux's `after-show-messages` option.
    pub const AFTER_SHOW_MESSAGES: &str = "after-show-messages";
    /// tmux's `after-show-options` option.
    pub const AFTER_SHOW_OPTIONS: &str = "after-show-options";
    /// tmux's `after-split-window` option.
    pub const AFTER_SPLIT_WINDOW: &str = "after-split-window";
    /// tmux's `after-unbind-key` option.
    pub const AFTER_UNBIND_KEY: &str = "after-unbind-key";
    /// tmux's `aggressive-resize` option.
    pub const AGGRESSIVE_RESIZE: &str = "aggressive-resize";
    /// tmux's `alert-activity` option.
    pub const ALERT_ACTIVITY: &str = "alert-activity";
    /// tmux's `alert-bell` option.
    pub const ALERT_BELL: &str = "alert-bell";
    /// tmux's `alert-silence` option.
    pub const ALERT_SILENCE: &str = "alert-silence";
    /// tmux's `allow-passthrough` option.
    pub const ALLOW_PASSTHROUGH: &str = "allow-passthrough";
    /// tmux's `allow-rename` option.
    pub const ALLOW_RENAME: &str = "allow-rename";
    /// tmux's `allow-set-title` option.
    pub const ALLOW_SET_TITLE: &str = "allow-set-title";
    /// tmux's `alternate-screen` option.
    pub const ALTERNATE_SCREEN: &str = "alternate-screen";
    /// tmux's `assume-paste-time` option.
    pub const ASSUME_PASTE_TIME: &str = "assume-paste-time";
    /// tmux's `automatic-rename` option.
    pub const AUTOMATIC_RENAME: &str = "automatic-rename";
    /// tmux's `automatic-rename-format` option.
    pub const AUTOMATIC_RENAME_FORMAT: &str = "automatic-rename-format";
    /// tmux's `backspace` option.
    pub const BACKSPACE: &str = "backspace";
    /// tmux's `base-index` option.
    pub const BASE_INDEX: &str = "base-index";
    /// tmux's `bell-action` option.
    pub const BELL_ACTION: &str = "bell-action";
    /// tmux's `buffer-limit` option.
    pub const BUFFER_LIMIT: &str = "buffer-limit";
    /// tmux's `client-active` option.
    pub const CLIENT_ACTIVE: &str = "client-active";
    /// tmux's `client-attached` option.
    pub const CLIENT_ATTACHED: &str = "client-attached";
    /// tmux's `client-dark-theme` option.
    pub const CLIENT_DARK_THEME: &str = "client-dark-theme";
    /// tmux's `client-detached` option.
    pub const CLIENT_DETACHED: &str = "client-detached";
    /// tmux's `client-focus-in` option.
    pub const CLIENT_FOCUS_IN: &str = "client-focus-in";
    /// tmux's `client-focus-out` option.
    pub const CLIENT_FOCUS_OUT: &str = "client-focus-out";
    /// tmux's `client-light-theme` option.
    pub const CLIENT_LIGHT_THEME: &str = "client-light-theme";
    /// tmux's `client-resized` option.
    pub const CLIENT_RESIZED: &str = "client-resized";
    /// tmux's `client-session-changed` option.
    pub const CLIENT_SESSION_CHANGED: &str = "client-session-changed";
    /// tmux's `clock-mode-colour` option.
    pub const CLOCK_MODE_COLOUR: &str = "clock-mode-colour";
    /// tmux's `clock-mode-style` option.
    pub const CLOCK_MODE_STYLE: &str = "clock-mode-style";
    /// tmux's `codepoint-widths` option.
    pub const CODEPOINT_WIDTHS: &str = "codepoint-widths";
    /// tmux's `command-alias` option.
    pub const COMMAND_ALIAS: &str = "command-alias";
    /// tmux's `command-error` option.
    pub const COMMAND_ERROR: &str = "command-error";
    /// tmux's `copy-command` option.
    pub const COPY_COMMAND: &str = "copy-command";
    /// tmux's `copy-mode-current-line-number-style` option.
    pub const COPY_MODE_CURRENT_LINE_NUMBER_STYLE: &str = "copy-mode-current-line-number-style";
    /// tmux's `copy-mode-current-match-style` option.
    pub const COPY_MODE_CURRENT_MATCH_STYLE: &str = "copy-mode-current-match-style";
    /// tmux's `copy-mode-line-number-style` option.
    pub const COPY_MODE_LINE_NUMBER_STYLE: &str = "copy-mode-line-number-style";
    /// tmux's `copy-mode-line-numbers` option.
    pub const COPY_MODE_LINE_NUMBERS: &str = "copy-mode-line-numbers";
    /// tmux's `copy-mode-mark-style` option.
    pub const COPY_MODE_MARK_STYLE: &str = "copy-mode-mark-style";
    /// tmux's `copy-mode-match-style` option.
    pub const COPY_MODE_MATCH_STYLE: &str = "copy-mode-match-style";
    /// tmux's `copy-mode-position-format` option.
    pub const COPY_MODE_POSITION_FORMAT: &str = "copy-mode-position-format";
    /// tmux's `copy-mode-position-style` option.
    pub const COPY_MODE_POSITION_STYLE: &str = "copy-mode-position-style";
    /// tmux's `copy-mode-selection-style` option.
    pub const COPY_MODE_SELECTION_STYLE: &str = "copy-mode-selection-style";
    /// tmux's `cursor-colour` option.
    pub const CURSOR_COLOUR: &str = "cursor-colour";
    /// tmux's `cursor-style` option.
    pub const CURSOR_STYLE: &str = "cursor-style";
    /// tmux's `default-client-command` option.
    pub const DEFAULT_CLIENT_COMMAND: &str = "default-client-command";
    /// tmux's `default-command` option.
    pub const DEFAULT_COMMAND: &str = "default-command";
    /// tmux's `default-shell` option.
    pub const DEFAULT_SHELL: &str = "default-shell";
    /// tmux's `default-size` option.
    pub const DEFAULT_SIZE: &str = "default-size";
    /// tmux's `default-terminal` option.
    pub const DEFAULT_TERMINAL: &str = "default-terminal";
    /// tmux's `destroy-unattached` option.
    pub const DESTROY_UNATTACHED: &str = "destroy-unattached";
    /// tmux's `detach-on-destroy` option.
    pub const DETACH_ON_DESTROY: &str = "detach-on-destroy";
    /// tmux's `display-panes-active-colour` option.
    pub const DISPLAY_PANES_ACTIVE_COLOUR: &str = "display-panes-active-colour";
    /// tmux's `display-panes-colour` option.
    pub const DISPLAY_PANES_COLOUR: &str = "display-panes-colour";
    /// tmux's `display-panes-time` option.
    pub const DISPLAY_PANES_TIME: &str = "display-panes-time";
    /// tmux's `display-time` option.
    pub const DISPLAY_TIME: &str = "display-time";
    /// tmux's `editor` option.
    pub const EDITOR: &str = "editor";
    /// tmux's `escape-time` option.
    pub const ESCAPE_TIME: &str = "escape-time";
    /// tmux's `exit-empty` option.
    pub const EXIT_EMPTY: &str = "exit-empty";
    /// tmux's `exit-unattached` option.
    pub const EXIT_UNATTACHED: &str = "exit-unattached";
    /// tmux's `extended-keys` option.
    pub const EXTENDED_KEYS: &str = "extended-keys";
    /// tmux's `extended-keys-format` option.
    pub const EXTENDED_KEYS_FORMAT: &str = "extended-keys-format";
    /// tmux's `fill-character` option.
    pub const FILL_CHARACTER: &str = "fill-character";
    /// tmux's `focus-events` option.
    pub const FOCUS_EVENTS: &str = "focus-events";
    /// tmux's `focus-follows-mouse` option.
    pub const FOCUS_FOLLOWS_MOUSE: &str = "focus-follows-mouse";
    /// tmux's `get-clipboard` option.
    pub const GET_CLIPBOARD: &str = "get-clipboard";
    /// tmux's `history-file` option.
    pub const HISTORY_FILE: &str = "history-file";
    /// tmux's `history-limit` option.
    pub const HISTORY_LIMIT: &str = "history-limit";
    /// tmux's `initial-repeat-time` option.
    pub const INITIAL_REPEAT_TIME: &str = "initial-repeat-time";
    /// tmux's `input-buffer-size` option.
    pub const INPUT_BUFFER_SIZE: &str = "input-buffer-size";
    /// tmux's `key-table` option.
    pub const KEY_TABLE: &str = "key-table";
    /// tmux's `lock-after-time` option.
    pub const LOCK_AFTER_TIME: &str = "lock-after-time";
    /// tmux's `lock-command` option.
    pub const LOCK_COMMAND: &str = "lock-command";
    /// tmux's `main-pane-height` option.
    pub const MAIN_PANE_HEIGHT: &str = "main-pane-height";
    /// tmux's `main-pane-width` option.
    pub const MAIN_PANE_WIDTH: &str = "main-pane-width";
    /// tmux's `menu-border-lines` option.
    pub const MENU_BORDER_LINES: &str = "menu-border-lines";
    /// tmux's `menu-border-style` option.
    pub const MENU_BORDER_STYLE: &str = "menu-border-style";
    /// tmux's `menu-selected-style` option.
    pub const MENU_SELECTED_STYLE: &str = "menu-selected-style";
    /// tmux's `menu-style` option.
    pub const MENU_STYLE: &str = "menu-style";
    /// tmux's `message-command-style` option.
    pub const MESSAGE_COMMAND_STYLE: &str = "message-command-style";
    /// tmux's `message-format` option.
    pub const MESSAGE_FORMAT: &str = "message-format";
    /// tmux's `message-limit` option.
    pub const MESSAGE_LIMIT: &str = "message-limit";
    /// tmux's `message-line` option.
    pub const MESSAGE_LINE: &str = "message-line";
    /// tmux's `message-style` option.
    pub const MESSAGE_STYLE: &str = "message-style";
    /// tmux's `mode-keys` option.
    pub const MODE_KEYS: &str = "mode-keys";
    /// tmux's `mode-style` option.
    pub const MODE_STYLE: &str = "mode-style";
    /// tmux's `monitor-activity` option.
    pub const MONITOR_ACTIVITY: &str = "monitor-activity";
    /// tmux's `monitor-bell` option.
    pub const MONITOR_BELL: &str = "monitor-bell";
    /// tmux's `monitor-silence` option.
    pub const MONITOR_SILENCE: &str = "monitor-silence";
    /// tmux's `mouse` option.
    pub const MOUSE: &str = "mouse";
    /// tmux's `other-pane-height` option.
    pub const OTHER_PANE_HEIGHT: &str = "other-pane-height";
    /// tmux's `other-pane-width` option.
    pub const OTHER_PANE_WIDTH: &str = "other-pane-width";
    /// tmux's `pane-active-border-style` option.
    pub const PANE_ACTIVE_BORDER_STYLE: &str = "pane-active-border-style";
    /// tmux's `pane-base-index` option.
    pub const PANE_BASE_INDEX: &str = "pane-base-index";
    /// tmux's `pane-border-format` option.
    pub const PANE_BORDER_FORMAT: &str = "pane-border-format";
    /// tmux's `pane-border-indicators` option.
    pub const PANE_BORDER_INDICATORS: &str = "pane-border-indicators";
    /// tmux's `pane-border-lines` option.
    pub const PANE_BORDER_LINES: &str = "pane-border-lines";
    /// tmux's `pane-border-status` option.
    pub const PANE_BORDER_STATUS: &str = "pane-border-status";
    /// tmux's `pane-border-style` option.
    pub const PANE_BORDER_STYLE: &str = "pane-border-style";
    /// tmux's `pane-colours` option.
    pub const PANE_COLOURS: &str = "pane-colours";
    /// tmux's `pane-died` option.
    pub const PANE_DIED: &str = "pane-died";
    /// tmux's `pane-exited` option.
    pub const PANE_EXITED: &str = "pane-exited";
    /// tmux's `pane-focus-in` option.
    pub const PANE_FOCUS_IN: &str = "pane-focus-in";
    /// tmux's `pane-focus-out` option.
    pub const PANE_FOCUS_OUT: &str = "pane-focus-out";
    /// tmux's `pane-mode-changed` option.
    pub const PANE_MODE_CHANGED: &str = "pane-mode-changed";
    /// tmux's `pane-scrollbars` option.
    pub const PANE_SCROLLBARS: &str = "pane-scrollbars";
    /// tmux's `pane-scrollbars-position` option.
    pub const PANE_SCROLLBARS_POSITION: &str = "pane-scrollbars-position";
    /// tmux's `pane-scrollbars-style` option.
    pub const PANE_SCROLLBARS_STYLE: &str = "pane-scrollbars-style";
    /// tmux's `pane-set-clipboard` option.
    pub const PANE_SET_CLIPBOARD: &str = "pane-set-clipboard";
    /// tmux's `pane-status-current-style` option.
    pub const PANE_STATUS_CURRENT_STYLE: &str = "pane-status-current-style";
    /// tmux's `pane-status-style` option.
    pub const PANE_STATUS_STYLE: &str = "pane-status-style";
    /// tmux's `pane-title-changed` option.
    pub const PANE_TITLE_CHANGED: &str = "pane-title-changed";
    /// tmux's `popup-border-lines` option.
    pub const POPUP_BORDER_LINES: &str = "popup-border-lines";
    /// tmux's `popup-border-style` option.
    pub const POPUP_BORDER_STYLE: &str = "popup-border-style";
    /// tmux's `popup-style` option.
    pub const POPUP_STYLE: &str = "popup-style";
    /// tmux's `prefix` option.
    pub const PREFIX: &str = "prefix";
    /// tmux's `prefix-timeout` option.
    pub const PREFIX_TIMEOUT: &str = "prefix-timeout";
    /// tmux's `prefix2` option.
    pub const PREFIX2: &str = "prefix2";
    /// tmux's `prompt-command-cursor-style` option.
    pub const PROMPT_COMMAND_CURSOR_STYLE: &str = "prompt-command-cursor-style";
    /// tmux's `prompt-cursor-colour` option.
    pub const PROMPT_CURSOR_COLOUR: &str = "prompt-cursor-colour";
    /// tmux's `prompt-cursor-style` option.
    pub const PROMPT_CURSOR_STYLE: &str = "prompt-cursor-style";
    /// tmux's `prompt-history-limit` option.
    pub const PROMPT_HISTORY_LIMIT: &str = "prompt-history-limit";
    /// tmux's `remain-on-exit` option.
    pub const REMAIN_ON_EXIT: &str = "remain-on-exit";
    /// tmux's `remain-on-exit-format` option.
    pub const REMAIN_ON_EXIT_FORMAT: &str = "remain-on-exit-format";
    /// tmux's `renumber-windows` option.
    pub const RENUMBER_WINDOWS: &str = "renumber-windows";
    /// tmux's `repeat-time` option.
    pub const REPEAT_TIME: &str = "repeat-time";
    /// tmux's `scroll-on-clear` option.
    pub const SCROLL_ON_CLEAR: &str = "scroll-on-clear";
    /// tmux's `session-closed` option.
    pub const SESSION_CLOSED: &str = "session-closed";
    /// tmux's `session-created` option.
    pub const SESSION_CREATED: &str = "session-created";
    /// tmux's `session-renamed` option.
    pub const SESSION_RENAMED: &str = "session-renamed";
    /// tmux's `session-status-current-style` option.
    pub const SESSION_STATUS_CURRENT_STYLE: &str = "session-status-current-style";
    /// tmux's `session-status-style` option.
    pub const SESSION_STATUS_STYLE: &str = "session-status-style";
    /// tmux's `session-window-changed` option.
    pub const SESSION_WINDOW_CHANGED: &str = "session-window-changed";
    /// tmux's `set-clipboard` option.
    pub const SET_CLIPBOARD: &str = "set-clipboard";
    /// tmux's `set-titles` option.
    pub const SET_TITLES: &str = "set-titles";
    /// tmux's `set-titles-string` option.
    pub const SET_TITLES_STRING: &str = "set-titles-string";
    /// tmux's `silence-action` option.
    pub const SILENCE_ACTION: &str = "silence-action";
    /// tmux's `status` option.
    pub const STATUS: &str = "status";
    /// tmux's `status-bg` option.
    pub const STATUS_BG: &str = "status-bg";
    /// tmux's `status-fg` option.
    pub const STATUS_FG: &str = "status-fg";
    /// tmux's `status-format` option.
    pub const STATUS_FORMAT: &str = "status-format";
    /// tmux's `status-interval` option.
    pub const STATUS_INTERVAL: &str = "status-interval";
    /// tmux's `status-justify` option.
    pub const STATUS_JUSTIFY: &str = "status-justify";
    /// tmux's `status-keys` option.
    pub const STATUS_KEYS: &str = "status-keys";
    /// tmux's `status-left` option.
    pub const STATUS_LEFT: &str = "status-left";
    /// tmux's `status-left-length` option.
    pub const STATUS_LEFT_LENGTH: &str = "status-left-length";
    /// tmux's `status-left-style` option.
    pub const STATUS_LEFT_STYLE: &str = "status-left-style";
    /// tmux's `status-position` option.
    pub const STATUS_POSITION: &str = "status-position";
    /// tmux's `status-right` option.
    pub const STATUS_RIGHT: &str = "status-right";
    /// tmux's `status-right-length` option.
    pub const STATUS_RIGHT_LENGTH: &str = "status-right-length";
    /// tmux's `status-right-style` option.
    pub const STATUS_RIGHT_STYLE: &str = "status-right-style";
    /// tmux's `status-style` option.
    pub const STATUS_STYLE: &str = "status-style";
    /// tmux's `synchronize-panes` option.
    pub const SYNCHRONIZE_PANES: &str = "synchronize-panes";
    /// tmux's `terminal-features` option.
    pub const TERMINAL_FEATURES: &str = "terminal-features";
    /// tmux's `terminal-overrides` option.
    pub const TERMINAL_OVERRIDES: &str = "terminal-overrides";
    /// tmux's `tiled-layout-max-columns` option.
    pub const TILED_LAYOUT_MAX_COLUMNS: &str = "tiled-layout-max-columns";
    /// tmux's `tree-mode-preview-format` option.
    pub const TREE_MODE_PREVIEW_FORMAT: &str = "tree-mode-preview-format";
    /// tmux's `tree-mode-preview-style` option.
    pub const TREE_MODE_PREVIEW_STYLE: &str = "tree-mode-preview-style";
    /// tmux's `update-environment` option.
    pub const UPDATE_ENVIRONMENT: &str = "update-environment";
    /// tmux's `user-keys` option.
    pub const USER_KEYS: &str = "user-keys";
    /// tmux's `variation-selector-always-wide` option.
    pub const VARIATION_SELECTOR_ALWAYS_WIDE: &str = "variation-selector-always-wide";
    /// tmux's `visual-activity` option.
    pub const VISUAL_ACTIVITY: &str = "visual-activity";
    /// tmux's `visual-bell` option.
    pub const VISUAL_BELL: &str = "visual-bell";
    /// tmux's `visual-silence` option.
    pub const VISUAL_SILENCE: &str = "visual-silence";
    /// tmux's `window-active-style` option.
    pub const WINDOW_ACTIVE_STYLE: &str = "window-active-style";
    /// tmux's `window-linked` option.
    pub const WINDOW_LINKED: &str = "window-linked";
    /// tmux's `window-pane-current-status-format` option.
    pub const WINDOW_PANE_CURRENT_STATUS_FORMAT: &str = "window-pane-current-status-format";
    /// tmux's `window-pane-status-format` option.
    pub const WINDOW_PANE_STATUS_FORMAT: &str = "window-pane-status-format";
    /// tmux's `window-size` option.
    pub const WINDOW_SIZE: &str = "window-size";
    /// tmux's `window-status-activity-style` option.
    pub const WINDOW_STATUS_ACTIVITY_STYLE: &str = "window-status-activity-style";
    /// tmux's `window-status-bell-style` option.
    pub const WINDOW_STATUS_BELL_STYLE: &str = "window-status-bell-style";
    /// tmux's `window-status-current-format` option.
    pub const WINDOW_STATUS_CURRENT_FORMAT: &str = "window-status-current-format";
    /// tmux's `window-status-current-style` option.
    pub const WINDOW_STATUS_CURRENT_STYLE: &str = "window-status-current-style";
    /// tmux's `window-status-format` option.
    pub const WINDOW_STATUS_FORMAT: &str = "window-status-format";
    /// tmux's `window-status-last-style` option.
    pub const WINDOW_STATUS_LAST_STYLE: &str = "window-status-last-style";
    /// tmux's `window-status-separator` option.
    pub const WINDOW_STATUS_SEPARATOR: &str = "window-status-separator";
    /// tmux's `window-status-style` option.
    pub const WINDOW_STATUS_STYLE: &str = "window-status-style";
    /// tmux's `window-style` option.
    pub const WINDOW_STYLE: &str = "window-style";
    /// tmux's `window-unlinked` option.
    pub const WINDOW_UNLINKED: &str = "window-unlinked";
    /// tmux's `word-separators` option.
    pub const WORD_SEPARATORS: &str = "word-separators";
    /// tmux's `wrap-search` option.
    pub const WRAP_SEARCH: &str = "wrap-search";
    /// tmux's `xterm-keys` option.
    pub const XTERM_KEYS: &str = "xterm-keys";
}
