//! What gathering a whole tmux hierarchy costs, measured against real tmux.
//!
//! ```console
//! $ cargo bench --features test-support
//! ```
//!
//! The claim under test is that [`libtmux::Server::hierarchy`] costs three
//! tmux commands whatever the server holds, where walking down costs one per
//! session and one per window. `tests/command_budget.rs` asserts the command
//! counts, which are exact; this reports what they cost in time, which is not.

// Helpers outside a test function are not covered by clippy.toml's
// in-test exemptions, and these files have them.
#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

use std::time::Duration;

use criterion::{BenchmarkId, Criterion, criterion_main};
use libtmux::test::TestServer;
use libtmux::{NewWindowOptions, Server, SplitDirection, SplitOptions};

/// One server shape to measure against.
struct Fixture {
    guard: TestServer,
    sessions: usize,
    windows: usize,
}

impl Fixture {
    fn server(&self) -> &Server {
        self.guard.server()
    }

    /// Describe the shape, so the report names objects rather than a number.
    fn label(&self) -> String {
        format!(
            "{}s{}w{}p",
            self.sessions,
            self.sessions * self.windows,
            self.sessions * self.windows * 2,
        )
    }
}

/// Build a server holding `sessions` sessions of `windows` two-pane windows.
async fn build(sessions: usize, windows: usize) -> Fixture {
    let guard = TestServer::builder().start().await.expect("tmux starts");

    for session in 0..sessions {
        let created = guard
            .server()
            .new_session(format!("bench-{session}").as_str())
            .await
            .expect("session");

        for window in 0..windows {
            let created = created
                .new_window(
                    NewWindowOptions::new(format!("window-{window}").as_str())
                        .command("sleep 3600"),
                )
                .await
                .expect("window");
            created
                .split(SplitOptions::new(SplitDirection::Below).command("sleep 3600"))
                .await
                .expect("pane");
        }
    }

    Fixture {
        guard,
        sessions,
        windows,
    }
}

/// Gather the hierarchy the obvious way, one listing per parent.
async fn walk(server: &Server) -> usize {
    let mut panes = 0;
    for session in server.sessions().await.expect("sessions") {
        for window in session.windows().await.expect("windows") {
            panes += window.panes().await.expect("panes").len();
        }
    }

    panes
}

fn hierarchy(criterion: &mut Criterion) {
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("a runtime");

    let mut group = criterion.benchmark_group("hierarchy");
    // Every sample spawns tmux processes, so the default sample count would
    // spend minutes measuring the same thing.
    group
        .sample_size(20)
        .measurement_time(Duration::from_secs(10));

    for (sessions, windows) in [(1, 1), (2, 4), (4, 8)] {
        let fixture = runtime.block_on(build(sessions, windows));
        let label = fixture.label();

        group.bench_with_input(
            BenchmarkId::new("gathered", &label),
            &fixture,
            |bench, fixture| {
                bench
                    .to_async(&runtime)
                    .iter(|| async { fixture.server().hierarchy().await.expect("hierarchy") });
            },
        );

        group.bench_with_input(
            BenchmarkId::new("walked", &label),
            &fixture,
            |bench, fixture| {
                bench
                    .to_async(&runtime)
                    .iter(|| async { walk(fixture.server()).await });
            },
        );

        runtime
            .block_on(fixture.guard.shutdown())
            .expect("tmux fixture shuts down");
    }

    group.finish();
}

/// Register the group. Generated by the macro, so it is documented here.
#[allow(missing_docs)]
mod generated {
    criterion::criterion_group!(benches, super::hierarchy);
}

use generated::benches;
criterion_main!(benches);
