#!/usr/bin/env python3

"""Generate the tmux option schema from tmux's own options-table.c.

tmux does not report an option's type over the command line, so the type has
to come from its source. Generating it keeps the table honest: rerun this
against a newer tmux and the diff shows exactly what changed.
"""

from __future__ import annotations

import pathlib
import re
import sys

TYPES = {
    "OPTIONS_TABLE_STRING": "Text",
    "OPTIONS_TABLE_NUMBER": "Number",
    "OPTIONS_TABLE_KEY": "Key",
    "OPTIONS_TABLE_COLOUR": "Colour",
    "OPTIONS_TABLE_FLAG": "Flag",
    "OPTIONS_TABLE_CHOICE": "Choice",
    "OPTIONS_TABLE_COMMAND": "Command",
}
SCOPES = {
    "OPTIONS_TABLE_SERVER": "Server",
    "OPTIONS_TABLE_SESSION": "Session",
    "OPTIONS_TABLE_WINDOW": "Window",
    "OPTIONS_TABLE_PANE": "Pane",
}

ENTRY = re.compile(
    r'\{\s*\.name\s*=\s*"(?P<name>[a-z0-9-]+)"'
    r'(?P<body>.*?)(?=\n\t\{\s*\.name|\n\t\{\s*\{|\Z)',
    re.S,
)


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate-option-schema.py <path to options-table.c>", file=sys.stderr)
        return 2

    source = pathlib.Path(sys.argv[1]).read_text()
    rows: list[tuple[str, str, str]] = []
    for match in ENTRY.finditer(source):
        body = match.group("body")
        kind = re.search(r"\.type\s*=\s*(OPTIONS_TABLE_[A-Z]+)", body)
        scope = re.search(r"\.scope\s*=\s*([A-Z_|]+)", body)
        if kind is None or kind.group(1) not in TYPES:
            continue
        # An option can be scoped to several tables; the first is enough to
        # say where it primarily lives.
        scopes = [] if scope is None else [
            SCOPES[part] for part in scope.group(1).split("|") if part in SCOPES
        ]
        rows.append((match.group("name"), TYPES[kind.group(1)], scopes[0] if scopes else "Server"))

    # Hooks are declared through macros rather than the struct form. Both
    # macros expand to a command-typed option; the pane variant is pane-scoped.
    for macro, scope in (("OPTIONS_TABLE_HOOK", "Session"), ("OPTIONS_TABLE_PANE_HOOK", "Pane")):
        for hook in re.finditer(rf'\n\t{macro}\("([a-z0-9-]+)"', source):
            rows.append((hook.group(1), "Command", scope))

    rows.sort()
    print("// @generated by scripts/generate-option-schema.py. Do not edit.")
    print("//")
    print("// Regenerate against a newer tmux to see exactly what changed:")
    print("//   python3 scripts/generate-option-schema.py <tmux>/options-table.c")
    print()
    print("use super::{OptionKind, OptionScope, OptionSchema};")
    print()
    print(f"/// Every option tmux's table declares, sorted by name.")
    print(f"pub(crate) static OPTION_SCHEMA: [OptionSchema; {len(rows)}] = [")
    for name, kind, scope in rows:
        print(
            f'    OptionSchema::new("{name}", OptionKind::{kind}, OptionScope::{scope}),'
        )
    print("];")
    print()
    print("/// Option names, so a typo is a compile error rather than a runtime one.")
    print("///")
    print("/// Every constant here is a name tmux declares. A user option, whose name")
    print("/// begins with `@`, has no constant because tmux does not declare one.")
    print("pub mod names {")
    seen: set[str] = set()
    for name, _, _ in rows:
        ident = name.upper().replace("-", "_")
        if ident in seen:
            continue
        seen.add(ident)
        print(f'    /// tmux\'s `{name}` option.')
        print(f'    pub const {ident}: &str = "{name}";')
    print("}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
