#!/usr/bin/env python3

"""Generate the tmux option schema from tmux's own options-table.c.

tmux does not report an option's type over the command line, so the type has
to come from its source. Generating it keeps the table honest: rerun this
against a newer tmux and the diff shows exactly what changed.
"""

from __future__ import annotations

import pathlib
import re
import sys

TYPES = {
    "OPTIONS_TABLE_STRING": "Text",
    "OPTIONS_TABLE_NUMBER": "Number",
    "OPTIONS_TABLE_KEY": "Key",
    "OPTIONS_TABLE_COLOUR": "Colour",
    "OPTIONS_TABLE_FLAG": "Flag",
    "OPTIONS_TABLE_CHOICE": "Choice",
    "OPTIONS_TABLE_COMMAND": "Command",
}
SCOPES = {
    "OPTIONS_TABLE_SERVER": "Server",
    "OPTIONS_TABLE_SESSION": "Session",
    "OPTIONS_TABLE_WINDOW": "Window",
    "OPTIONS_TABLE_PANE": "Pane",
}

ENTRY = re.compile(
    r'\{\s*\.name\s*=\s*"(?P<name>[a-z0-9-]+)"'
    r'(?P<body>.*?)(?=\n\t\{\s*\.name|\n\t\{\s*\{|\Z)',
    re.S,
)
CHOICE_LIST = re.compile(r"static const char \*(\w+)\[\] = \{(.*?)\};", re.S)
DEFINE = re.compile(r"^#define\s+(\w+)\s+(\d+)\s*$", re.M)

# The limits tmux's table spells as <limits.h> names. The rest are defined in
# tmux.h beside the table and read from there.
LIMITS = {
    "INT_MAX": 2**31 - 1,
    "SHRT_MAX": 2**15 - 1,
    "UINT_MAX": 2**32 - 1,
    "USHRT_MAX": 2**16 - 1,
}


def bound(text: str, defines: dict[str, int]) -> int:
    text = text.strip()
    if re.fullmatch(r"-?\d+", text):
        return int(text)
    if text in LIMITS:
        return LIMITS[text]
    if text in defines:
        return defines[text]
    raise SystemExit(f"cannot resolve the bound {text!r}")


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate-option-schema.py <path to options-table.c>", file=sys.stderr)
        return 2

    table = pathlib.Path(sys.argv[1])
    source = table.read_text()
    header = table.with_name("tmux.h")
    defines = {
        name: int(value)
        for name, value in DEFINE.findall(header.read_text() if header.exists() else "")
    }
    choice_lists = {
        name: tuple(re.findall(r'"([^"]*)"', body))
        for name, body in CHOICE_LIST.findall(source)
    }

    rows: list[tuple[str, str, tuple[str, ...], tuple[str, ...], tuple[int, int] | None]] = []
    for match in ENTRY.finditer(source):
        body = match.group("body")
        kind = re.search(r"\.type\s*=\s*(OPTIONS_TABLE_[A-Z]+)", body)
        scope = re.search(r"\.scope\s*=\s*([A-Z_|]+)", body)
        if kind is None or kind.group(1) not in TYPES:
            continue
        # An option can be scoped to several tables, and tmux names no primary
        # among them: `remain-on-exit` is window and pane both, and a write is
        # legal at either. Keeping one would decide that question wrongly.
        scopes = [] if scope is None else [
            SCOPES[part] for part in scope.group(1).split("|") if part in SCOPES
        ]

        choices: tuple[str, ...] = ()
        if kind.group(1) == "OPTIONS_TABLE_CHOICE":
            listed = re.search(r"\.choices\s*=\s*(\w+)", body)
            if listed is None or listed.group(1) not in choice_lists:
                raise SystemExit(f"{match.group('name')}: a choice with no list")
            choices = choice_lists[listed.group(1)]

        # tmux checks a number with strtonum(value, minimum, maximum), and an
        # absent bound is zero, so a number without both would take only 0.
        limits = None
        if kind.group(1) == "OPTIONS_TABLE_NUMBER":
            low = re.search(r"\.minimum\s*=\s*([^,\n]+)", body)
            high = re.search(r"\.maximum\s*=\s*([^,\n]+)", body)
            if low is None or high is None:
                raise SystemExit(f"{match.group('name')}: a number with no range")
            limits = (bound(low.group(1), defines), bound(high.group(1), defines))

        rows.append((
            match.group("name"),
            TYPES[kind.group(1)],
            tuple(scopes or ["Server"]),
            choices,
            limits,
        ))

    # Hooks are declared through macros rather than the struct form. Both
    # expand to a command-typed option. The pane variant declares
    # `OPTIONS_TABLE_WINDOW|OPTIONS_TABLE_PANE`, not pane alone, and has since
    # 3.2a: `set-hook -w` on one is accepted and read back at window scope.
    for macro, scopes in (
        ("OPTIONS_TABLE_HOOK", ("Session",)),
        ("OPTIONS_TABLE_PANE_HOOK", ("Window", "Pane")),
    ):
        for hook in re.finditer(rf'\n\t{macro}\("([a-z0-9-]+)"', source):
            rows.append((hook.group(1), "Command", scopes, (), None))

    # tmux resolves a handful of legacy spellings before it looks a name up,
    # so a caller reaching an option through one reaches the same option.
    aliases = sorted(
        re.findall(r'\{ "([a-z0-9-]+)", "([a-z0-9-]+)" \}', source)
    )

    rows.sort()
    print("// @generated by scripts/generate-option-schema.py. Do not edit.")
    print("//")
    print("// Regenerate against a newer tmux to see exactly what changed:")
    print("//   python3 scripts/generate-option-schema.py <tmux>/options-table.c")
    print()
    print("use super::{OptionKind, OptionScope, OptionSchema};")
    print()
    print(f"/// Every option tmux's table declares, sorted by name.")
    print(f"pub(crate) static OPTION_SCHEMA: [OptionSchema; {len(rows)}] = [")
    for name, kind, scopes, choices, limits in rows:
        rendered = ", ".join(f"OptionScope::{scope}" for scope in scopes)
        entry = f'OptionSchema::new("{name}", OptionKind::{kind}, &[{rendered}])'
        if choices:
            words = ", ".join(f'"{choice}"' for choice in choices)
            entry += f".with_choices(&[{words}])"
        if limits is not None:
            entry += f".with_range({limits[0]:_}, {limits[1]:_})"
        print(f"    {entry},")
    print("];")
    print()
    print("/// The spellings tmux maps to another option before looking it up.")
    print(f"pub(crate) static OPTION_ALIASES: [(&str, &str); {len(aliases)}] = [")
    for old_name, new_name in aliases:
        print(f'    ("{old_name}", "{new_name}"),')
    print("];")
    print()
    print("/// Option names, so a typo is a compile error rather than a runtime one.")
    print("///")
    print("/// Every constant here is a name tmux declares. A user option, whose name")
    print("/// begins with `@`, has no constant because tmux does not declare one.")
    print("pub mod names {")
    seen: set[str] = set()
    for name, *_ in rows:
        ident = name.upper().replace("-", "_")
        if ident in seen:
            continue
        seen.add(ident)
        print(f'    /// tmux\'s `{name}` option.')
        print(f'    pub const {ident}: &str = "{name}";')
    print("}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
