//! The generated MCP tool reference follows the authoritative registry.

#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::error::Error;
use std::fmt::Write as _;
use std::path::Path;

use tmux_mcp::{Selection, TmuxTools};

type TestResult<T = ()> = Result<T, Box<dyn Error>>;

fn generated_reference() -> TestResult<String> {
    let tools = TmuxTools::builder(libtmux::Server::new()?)
        .selection(Selection::parse(
            Some("inspect,manage,execute,teardown"),
            None,
            None,
        )?)
        .build();
    let mut output = String::from(
        "# tmux MCP tool reference\n\nGenerated from the authoritative native registry. Do not edit this file by hand.\nRefresh it with `LIBTMUX_RERECORD=1 cargo test --locked -p tmux-mcp --test docs generated_tool_reference_is_current`.\n",
    );
    for tool in tools.offered() {
        let row = tool
            .meta
            .as_ref()
            .and_then(|meta| meta.0.get("com.git-pull.libtmux-mcp/capability"))
            .expect("capability row");
        writeln!(output, "\n## `{}`\n", tool.name)?;
        writeln!(
            output,
            "{}\n",
            tool.description.as_deref().expect("controlled description")
        )?;
        writeln!(output, "- Toolset: `{}`", row["toolset"].as_str().unwrap())?;
        writeln!(
            output,
            "- Process reach: `{}`",
            row["processReach"].as_str().unwrap()
        )?;
        writeln!(
            output,
            "- Tmux effects: `{}`",
            serde_json::to_string(&row["tmuxEffects"])?
        )?;
        writeln!(
            output,
            "- Output classes: `{}`",
            serde_json::to_string(&row["outputClasses"])?
        )?;
        writeln!(
            output,
            "- May expose secrets: `{}`",
            row["mayExposeSecrets"].as_bool().unwrap()
        )?;
        writeln!(
            output,
            "- May return untrusted content: `{}`",
            row["mayReturnUntrustedContent"].as_bool().unwrap()
        )?;
        writeln!(
            output,
            "- Whole-call annotations: `{}`",
            serde_json::to_string(&row["annotations"])?
        )?;
        writeln!(
            output,
            "- Input literalization: `{}`",
            serde_json::to_string(&row["inputLiteralization"])?
        )?;
        writeln!(
            output,
            "- Nested authority: `{}`",
            serde_json::to_string(&row["nestedAuthority"])?
        )?;
        writeln!(
            output,
            "- Amplifies future input: `{}`",
            row["amplifiesFutureInput"].as_bool().unwrap()
        )?;
    }
    Ok(output)
}

#[test]
fn generated_tool_reference_is_current() -> TestResult {
    let expected = generated_reference()?;
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("TOOLS.md");
    if std::env::var_os("LIBTMUX_RERECORD").is_some() {
        std::fs::write(&path, &expected)?;
    }
    let actual = std::fs::read_to_string(path).unwrap_or_default();

    assert_eq!(
        actual, expected,
        "set LIBTMUX_RERECORD=1 to refresh TOOLS.md"
    );
    Ok(())
}

#[test]
fn readme_links_to_the_generated_reference_without_copying_the_inventory() -> TestResult {
    let readme = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("README.md"))?;

    assert!(readme.contains("[generated tool reference](TOOLS.md)"));
    assert!(!readme.contains("**Inspect (18):**"));
    Ok(())
}
